# Copyright (c) 2015 
# Author: Xerxes Wu
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


PRECISION = 2

NO_STRATEGY = "no_strategy"
HIGH = "high"
LOW = "low"

MAX_INVENTORY_SIZE = 20
TICK_SIZE = 0.01
DAY_20_BREAKOUT = "20"
DAY_55_BREAKOUT = "55"
NOT_ENOUGH_DATA = -1 
NONE = "none"
DAY_20 = 20
DAY_55 = 55
DAY_10_EXIT = 10
DAY_20_EXIT = 20
SYS_1_EXIT = 10
SYS_2_EXIT = 20
SYS_1_ENTRY_RATIO = 0.5
SYS_2_ENTRY_RATIO = 0.5
MAX_SYS_1_ENTRIES = MAX_INVENTORY_SIZE * SYS_1_ENTRY_RATIO
MAX_SYS_2_ENTRIES = MAX_INVENTORY_SIZE * SYS_2_ENTRY_RATIO


SYS_1_LONG = 0 
SYS_1_SHORT = 1
SYS_2_LONG = 2
SYS_2_SHORT = 3
LONG = 4
SHORT = 5
